//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adresat.Institucionet {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adresat.org/", ConfigurationName="Institucionet.Sherbimi_InstitucionetSoap")]
    public interface Sherbimi_InstitucionetSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/validoNrInstitucionit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string validoNrInstitucionit(string NrInstitucionit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/validoNrInstitucionit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> validoNrInstitucionitAsync(string NrInstitucionit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoInstitucionet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string lexoInstitucionet(string NrInstitucionit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoInstitucionet", ReplyAction="*")]
        System.Threading.Tasks.Task<string> lexoInstitucionetAsync(string NrInstitucionit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoInstitucionetQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet lexoInstitucionetQuery(string Emri, string Telefoni, string Lloji);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoInstitucionetQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> lexoInstitucionetQueryAsync(string Emri, string Telefoni, string Lloji);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Sherbimi_InstitucionetSoapChannel : Adresat.Institucionet.Sherbimi_InstitucionetSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Sherbimi_InstitucionetSoapClient : System.ServiceModel.ClientBase<Adresat.Institucionet.Sherbimi_InstitucionetSoap>, Adresat.Institucionet.Sherbimi_InstitucionetSoap {
        
        public Sherbimi_InstitucionetSoapClient() {
        }
        
        public Sherbimi_InstitucionetSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Sherbimi_InstitucionetSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sherbimi_InstitucionetSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sherbimi_InstitucionetSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string validoNrInstitucionit(string NrInstitucionit) {
            return base.Channel.validoNrInstitucionit(NrInstitucionit);
        }
        
        public System.Threading.Tasks.Task<string> validoNrInstitucionitAsync(string NrInstitucionit) {
            return base.Channel.validoNrInstitucionitAsync(NrInstitucionit);
        }
        
        public string lexoInstitucionet(string NrInstitucionit) {
            return base.Channel.lexoInstitucionet(NrInstitucionit);
        }
        
        public System.Threading.Tasks.Task<string> lexoInstitucionetAsync(string NrInstitucionit) {
            return base.Channel.lexoInstitucionetAsync(NrInstitucionit);
        }
        
        public System.Data.DataSet lexoInstitucionetQuery(string Emri, string Telefoni, string Lloji) {
            return base.Channel.lexoInstitucionetQuery(Emri, Telefoni, Lloji);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> lexoInstitucionetQueryAsync(string Emri, string Telefoni, string Lloji) {
            return base.Channel.lexoInstitucionetQueryAsync(Emri, Telefoni, Lloji);
        }
    }
}
