//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adresat.Arbk {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adresat.org/", ConfigurationName="Arbk.Sherbimi_ArbkSoap")]
    public interface Sherbimi_ArbkSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/validoNrBiznesit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string validoNrBiznesit(string NrBiznesit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/validoNrBiznesit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> validoNrBiznesitAsync(string NrBiznesit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoArbk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string lexoArbk(string NrBiznesit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoArbk", ReplyAction="*")]
        System.Threading.Tasks.Task<string> lexoArbkAsync(string NrBiznesit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoArbkQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet lexoArbkQuery(string Emri, string NrLeternjoftimit, string AktivitetiKryesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoArbkQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> lexoArbkQueryAsync(string Emri, string NrLeternjoftimit, string AktivitetiKryesor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Sherbimi_ArbkSoapChannel : Adresat.Arbk.Sherbimi_ArbkSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Sherbimi_ArbkSoapClient : System.ServiceModel.ClientBase<Adresat.Arbk.Sherbimi_ArbkSoap>, Adresat.Arbk.Sherbimi_ArbkSoap {
        
        public Sherbimi_ArbkSoapClient() {
        }
        
        public Sherbimi_ArbkSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Sherbimi_ArbkSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sherbimi_ArbkSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sherbimi_ArbkSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string validoNrBiznesit(string NrBiznesit) {
            return base.Channel.validoNrBiznesit(NrBiznesit);
        }
        
        public System.Threading.Tasks.Task<string> validoNrBiznesitAsync(string NrBiznesit) {
            return base.Channel.validoNrBiznesitAsync(NrBiznesit);
        }
        
        public string lexoArbk(string NrBiznesit) {
            return base.Channel.lexoArbk(NrBiznesit);
        }
        
        public System.Threading.Tasks.Task<string> lexoArbkAsync(string NrBiznesit) {
            return base.Channel.lexoArbkAsync(NrBiznesit);
        }
        
        public System.Data.DataSet lexoArbkQuery(string Emri, string NrLeternjoftimit, string AktivitetiKryesor) {
            return base.Channel.lexoArbkQuery(Emri, NrLeternjoftimit, AktivitetiKryesor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> lexoArbkQueryAsync(string Emri, string NrLeternjoftimit, string AktivitetiKryesor) {
            return base.Channel.lexoArbkQueryAsync(Emri, NrLeternjoftimit, AktivitetiKryesor);
        }
    }
}
