//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adresat.RegjistriCivil {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adresat.org/", ConfigurationName="RegjistriCivil.SherbimiSoap")]
    public interface SherbimiSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/validoNrPersonal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string validoNrPersonal(string NrPersonal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/validoNrPersonal", ReplyAction="*")]
        System.Threading.Tasks.Task<string> validoNrPersonalAsync(string NrPersonal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoRegjistrinCivil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string lexoRegjistrinCivil(string NrPersonal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoRegjistrinCivil", ReplyAction="*")]
        System.Threading.Tasks.Task<string> lexoRegjistrinCivilAsync(string NrPersonal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoRegjistringCivilQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet lexoRegjistringCivilQuery(string Emri, string Mbiemri, string DataLindjes, string VendiLindjes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adresat.org/lexoRegjistringCivilQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> lexoRegjistringCivilQueryAsync(string Emri, string Mbiemri, string DataLindjes, string VendiLindjes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SherbimiSoapChannel : Adresat.RegjistriCivil.SherbimiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SherbimiSoapClient : System.ServiceModel.ClientBase<Adresat.RegjistriCivil.SherbimiSoap>, Adresat.RegjistriCivil.SherbimiSoap {
        
        public SherbimiSoapClient() {
        }
        
        public SherbimiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SherbimiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SherbimiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SherbimiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string validoNrPersonal(string NrPersonal) {
            return base.Channel.validoNrPersonal(NrPersonal);
        }
        
        public System.Threading.Tasks.Task<string> validoNrPersonalAsync(string NrPersonal) {
            return base.Channel.validoNrPersonalAsync(NrPersonal);
        }
        
        public string lexoRegjistrinCivil(string NrPersonal) {
            return base.Channel.lexoRegjistrinCivil(NrPersonal);
        }
        
        public System.Threading.Tasks.Task<string> lexoRegjistrinCivilAsync(string NrPersonal) {
            return base.Channel.lexoRegjistrinCivilAsync(NrPersonal);
        }
        
        public System.Data.DataSet lexoRegjistringCivilQuery(string Emri, string Mbiemri, string DataLindjes, string VendiLindjes) {
            return base.Channel.lexoRegjistringCivilQuery(Emri, Mbiemri, DataLindjes, VendiLindjes);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> lexoRegjistringCivilQueryAsync(string Emri, string Mbiemri, string DataLindjes, string VendiLindjes) {
            return base.Channel.lexoRegjistringCivilQueryAsync(Emri, Mbiemri, DataLindjes, VendiLindjes);
        }
    }
}
