//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adresat.RegjistriCivil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegjistriCivil.SherbimiSoap")]
    public interface SherbimiSoap {
        
        // CODEGEN: Generating message contract since element name NrPersonal from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validoNrPersonal", ReplyAction="*")]
        Adresat.RegjistriCivil.validoNrPersonalResponse validoNrPersonal(Adresat.RegjistriCivil.validoNrPersonalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validoNrPersonal", ReplyAction="*")]
        System.Threading.Tasks.Task<Adresat.RegjistriCivil.validoNrPersonalResponse> validoNrPersonalAsync(Adresat.RegjistriCivil.validoNrPersonalRequest request);
        
        // CODEGEN: Generating message contract since element name NrPersonal from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lexoRegjistrinCivil", ReplyAction="*")]
        Adresat.RegjistriCivil.lexoRegjistrinCivilResponse lexoRegjistrinCivil(Adresat.RegjistriCivil.lexoRegjistrinCivilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lexoRegjistrinCivil", ReplyAction="*")]
        System.Threading.Tasks.Task<Adresat.RegjistriCivil.lexoRegjistrinCivilResponse> lexoRegjistrinCivilAsync(Adresat.RegjistriCivil.lexoRegjistrinCivilRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validoNrPersonalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validoNrPersonal", Namespace="http://tempuri.org/", Order=0)]
        public Adresat.RegjistriCivil.validoNrPersonalRequestBody Body;
        
        public validoNrPersonalRequest() {
        }
        
        public validoNrPersonalRequest(Adresat.RegjistriCivil.validoNrPersonalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validoNrPersonalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NrPersonal;
        
        public validoNrPersonalRequestBody() {
        }
        
        public validoNrPersonalRequestBody(string NrPersonal) {
            this.NrPersonal = NrPersonal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validoNrPersonalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validoNrPersonalResponse", Namespace="http://tempuri.org/", Order=0)]
        public Adresat.RegjistriCivil.validoNrPersonalResponseBody Body;
        
        public validoNrPersonalResponse() {
        }
        
        public validoNrPersonalResponse(Adresat.RegjistriCivil.validoNrPersonalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validoNrPersonalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validoNrPersonalResult;
        
        public validoNrPersonalResponseBody() {
        }
        
        public validoNrPersonalResponseBody(string validoNrPersonalResult) {
            this.validoNrPersonalResult = validoNrPersonalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lexoRegjistrinCivilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lexoRegjistrinCivil", Namespace="http://tempuri.org/", Order=0)]
        public Adresat.RegjistriCivil.lexoRegjistrinCivilRequestBody Body;
        
        public lexoRegjistrinCivilRequest() {
        }
        
        public lexoRegjistrinCivilRequest(Adresat.RegjistriCivil.lexoRegjistrinCivilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class lexoRegjistrinCivilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NrPersonal;
        
        public lexoRegjistrinCivilRequestBody() {
        }
        
        public lexoRegjistrinCivilRequestBody(string NrPersonal) {
            this.NrPersonal = NrPersonal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lexoRegjistrinCivilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lexoRegjistrinCivilResponse", Namespace="http://tempuri.org/", Order=0)]
        public Adresat.RegjistriCivil.lexoRegjistrinCivilResponseBody Body;
        
        public lexoRegjistrinCivilResponse() {
        }
        
        public lexoRegjistrinCivilResponse(Adresat.RegjistriCivil.lexoRegjistrinCivilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class lexoRegjistrinCivilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lexoRegjistrinCivilResult;
        
        public lexoRegjistrinCivilResponseBody() {
        }
        
        public lexoRegjistrinCivilResponseBody(string lexoRegjistrinCivilResult) {
            this.lexoRegjistrinCivilResult = lexoRegjistrinCivilResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SherbimiSoapChannel : Adresat.RegjistriCivil.SherbimiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SherbimiSoapClient : System.ServiceModel.ClientBase<Adresat.RegjistriCivil.SherbimiSoap>, Adresat.RegjistriCivil.SherbimiSoap {
        
        public SherbimiSoapClient() {
        }
        
        public SherbimiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SherbimiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SherbimiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SherbimiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Adresat.RegjistriCivil.validoNrPersonalResponse Adresat.RegjistriCivil.SherbimiSoap.validoNrPersonal(Adresat.RegjistriCivil.validoNrPersonalRequest request) {
            return base.Channel.validoNrPersonal(request);
        }
        
        public string validoNrPersonal(string NrPersonal) {
            Adresat.RegjistriCivil.validoNrPersonalRequest inValue = new Adresat.RegjistriCivil.validoNrPersonalRequest();
            inValue.Body = new Adresat.RegjistriCivil.validoNrPersonalRequestBody();
            inValue.Body.NrPersonal = NrPersonal;
            Adresat.RegjistriCivil.validoNrPersonalResponse retVal = ((Adresat.RegjistriCivil.SherbimiSoap)(this)).validoNrPersonal(inValue);
            return retVal.Body.validoNrPersonalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Adresat.RegjistriCivil.validoNrPersonalResponse> Adresat.RegjistriCivil.SherbimiSoap.validoNrPersonalAsync(Adresat.RegjistriCivil.validoNrPersonalRequest request) {
            return base.Channel.validoNrPersonalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Adresat.RegjistriCivil.validoNrPersonalResponse> validoNrPersonalAsync(string NrPersonal) {
            Adresat.RegjistriCivil.validoNrPersonalRequest inValue = new Adresat.RegjistriCivil.validoNrPersonalRequest();
            inValue.Body = new Adresat.RegjistriCivil.validoNrPersonalRequestBody();
            inValue.Body.NrPersonal = NrPersonal;
            return ((Adresat.RegjistriCivil.SherbimiSoap)(this)).validoNrPersonalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Adresat.RegjistriCivil.lexoRegjistrinCivilResponse Adresat.RegjistriCivil.SherbimiSoap.lexoRegjistrinCivil(Adresat.RegjistriCivil.lexoRegjistrinCivilRequest request) {
            return base.Channel.lexoRegjistrinCivil(request);
        }
        
        public string lexoRegjistrinCivil(string NrPersonal) {
            Adresat.RegjistriCivil.lexoRegjistrinCivilRequest inValue = new Adresat.RegjistriCivil.lexoRegjistrinCivilRequest();
            inValue.Body = new Adresat.RegjistriCivil.lexoRegjistrinCivilRequestBody();
            inValue.Body.NrPersonal = NrPersonal;
            Adresat.RegjistriCivil.lexoRegjistrinCivilResponse retVal = ((Adresat.RegjistriCivil.SherbimiSoap)(this)).lexoRegjistrinCivil(inValue);
            return retVal.Body.lexoRegjistrinCivilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Adresat.RegjistriCivil.lexoRegjistrinCivilResponse> Adresat.RegjistriCivil.SherbimiSoap.lexoRegjistrinCivilAsync(Adresat.RegjistriCivil.lexoRegjistrinCivilRequest request) {
            return base.Channel.lexoRegjistrinCivilAsync(request);
        }
        
        public System.Threading.Tasks.Task<Adresat.RegjistriCivil.lexoRegjistrinCivilResponse> lexoRegjistrinCivilAsync(string NrPersonal) {
            Adresat.RegjistriCivil.lexoRegjistrinCivilRequest inValue = new Adresat.RegjistriCivil.lexoRegjistrinCivilRequest();
            inValue.Body = new Adresat.RegjistriCivil.lexoRegjistrinCivilRequestBody();
            inValue.Body.NrPersonal = NrPersonal;
            return ((Adresat.RegjistriCivil.SherbimiSoap)(this)).lexoRegjistrinCivilAsync(inValue);
        }
    }
}
